CREATE DATABASE IF NOT EXISTS Glass;

CREATE TABLE IF NOT EXISTS Employee (
    id SMALLINT UNSIGNED PRIMARY KEY UNIQUE AUTO_INCREMENT NOT NULL,
    name VARCHAR(40) NOT NULL,
    cpf VARCHAR(11) NOT NULL UNIQUE,
    rg VARCHAR(9) DEFAULT '',
    birthday DATE NOT NULL,
    phone VARCHAR(13) DEFAULT '',
    password VARCHAR(255) NOT NULL,
    admin TINYINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS Appointment (
    id SMALLINT UNSIGNED PRIMARY KEY UNIQUE AUTO_INCREMENT NOT NULL,
    appointmentDate DATE NOT NULL,
    appointmentType VARCHAR(30) DEFAULT '',
    employeeId SMALLINT UNSIGNED NOT NULL,
    patientId SMALLINT UNSIGNED NOT NULL,
    roomId SMALLINT UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS Room (
    id SMALLINT UNSIGNED PRIMARY KEY UNIQUE AUTO_INCREMENT NOT NULL,
    name VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS Patient (
    id SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL UNIQUE,
    fullName VARCHAR(40) NOT NULL,
    birthday DATE NOT NULL,
    cpf VARCHAR(11) NOT NULL UNIQUE,
    rg VARCHAR(9) DEFAULT '',
    phone VARCHAR(13) DEFAULT ''
);

CREATE TABLE IF NOT EXISTS Record (
    id SMALLINT UNSIGNED PRIMARY KEY UNIQUE AUTO_INCREMENT NOT NULL,
    allergies TEXT DEFAULT '',
    annotations TEXT DEFAULT '',
    patientId SMALLINT UNSIGNED NOT NULL
);

/* CREATE TABLE IF NOT EXISTS TaskCard (
    id SMALLINT UNSIGNED PRIMARY KEY UNIQUE AUTO_INCREMENT NOT NULL,
    title VARCHAR(40) NOT NULL,
    description TEXT DEFAULT '',
    creationDate DATE DEFAULT (CURRENT_TIMESTAMP),
    priority TINYINT DEFAULT 0,
    creator VARCHAR(40) NOT NULL,
    taskColumnId SMALLINT UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS TaskColumn (
    id SMALLINT UNSIGNED PRIMARY KEY UNIQUE AUTO_INCREMENT NOT NULL,
    title VARCHAR(40) NOT NULL,
    columnOrder TINYINT NOT NULL
); */

CREATE TABLE IF NOT EXISTS Schedule (
	id SMALLINT UNSIGNED PRIMARY KEY UNIQUE AUTO_INCREMENT NOT NULL,
    dayOfWeek TINYINT UNSIGNED NOT NULL,
    startTime TIME NOT NULL,
    endTime TIME NOT NULL,
    frequency TINYINT NOT NULL DEFAULT -1,
    employeeId SMALLINT UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS EventualSchedule (
	id SMALLINT UNSIGNED PRIMARY KEY UNIQUE AUTO_INCREMENT NOT NULL,
    eventualDate DATE NOT NULL,
    startTime TIME NOT NULL,
    endTime TIME NOT NULL,
    frequency TINYINT NOT NULL DEFAULT -1,
    eventualState TINYINT UNSIGNED NOT NULL, 
    employeeId SMALLINT UNSIGNED NOT NULL	
);
 
ALTER TABLE Appointment
    ADD FOREIGN KEY (employeeId) REFERENCES Employee(id) ON DELETE CASCADE ON UPDATE CASCADE,
    ADD FOREIGN KEY (patientId) REFERENCES Patient(id) ON DELETE CASCADE ON UPDATE CASCADE,
    ADD FOREIGN KEY (roomId) REFERENCES Room(id) ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE Record 
    ADD FOREIGN KEY (patientId) REFERENCES Patient(id) ON DELETE CASCADE ON UPDATE CASCADE;
 
/* ALTER TABLE TaskCard
    ADD FOREIGN KEY (taskColumnId) REFERENCES TaskColumn(id) ON DELETE CASCADE ON UPDATE CASCADE; */

ALTER TABLE Schedule
    ADD FOREIGN KEY (employeeId) REFERENCES Employee(id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE EventualSchedule
    ADD FOREIGN KEY (employeeId) REFERENCES Employee(id) ON DELETE CASCADE ON UPDATE CASCADE;
